/* 과목 데이터 */
INSERT INTO SUBJECTS(TITLE) VALUES('자바');
INSERT INTO SUBJECTS(TITLE) VALUES('C');
INSERT INTO SUBJECTS(TITLE) VALUES('C++');
INSERT INTO SUBJECTS(TITLE) VALUES('C#');
INSERT INTO SUBJECTS(TITLE) VALUES('안드로이드');
INSERT INTO SUBJECTS(TITLE) VALUES('HTML5');
INSERT INTO SUBJECTS(TITLE) VALUES('아두이노');
INSERT INTO SUBJECTS(TITLE) VALUES('서블릿/JSP');
INSERT INTO SUBJECTS(TITLE) VALUES('스프링 프레임워크');

/* 강사 데이터 */
INSERT INTO TRAINERS(NAME,PHOTO,TEL,EMAIL,PWD)
VALUES('홍길동','hong.gif','111-1111','hong@test.com','1111');
INSERT INTO TRAINERS(NAME,PHOTO,TEL,EMAIL,PWD)
VALUES('임꺽정','leem.gif','111-2222','leem@test.com','1111');
INSERT INTO TRAINERS(NAME,PHOTO,TEL,EMAIL,PWD)
VALUES('유관순','yoo.gif','111-3333','yoo@test.com','1111');
INSERT INTO TRAINERS(NAME,PHOTO,TEL,EMAIL,PWD)
VALUES('안중근','ahn.gif','111-4444','ahn@test.com','1111');
INSERT INTO TRAINERS(NAME,PHOTO,TEL,EMAIL,PWD)
VALUES('윤봉길','yoon.gif','111-5555','yoon@test.com','1111');

/* 강사가 강의할 수 있는 과목 데이터 */
/*홍길동 : 자바, C, C++*/
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(1,1);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(1,2);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(1,3);

/*임꺽정 : 안드로이디, 아두이노*/
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(2,5);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(2,7);

/*유관순 : 자바, HTML5*/
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(3,1);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(3,6);

/*안중근 : 자바, C, C++, 안드로이드, 아두이노*/
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(4,1);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(4,2);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(4,3);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(4,5);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(4,7);

/*윤봉길 : 자바, 서블릿JSP, 스프링 프레임워크 */
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(5,1);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(5,8);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(5,9);

/* 강의 데이터 */
INSERT INTO LECTURES(TITLE,CAPA,ST_DATE,ED_DATE,HOURS,DAYS)
VALUES('[자바70]자바고급과정',30,'2015-01-02','2015-05-31',800,100);
INSERT INTO LECTURES(TITLE,CAPA,ST_DATE,ED_DATE,HOURS,DAYS)
VALUES('[자바71]자바고급과정',30,'2015-02-01','2015-06-30',800,100);
INSERT INTO LECTURES(TITLE,CAPA,ST_DATE,ED_DATE,HOURS,DAYS)
VALUES('[자바72]자바고급과정',30,'2015-03-02','2015-07-31',800,100);
INSERT INTO LECTURES(TITLE,CAPA,ST_DATE,ED_DATE,HOURS,DAYS)
VALUES('[윈도우50]윈도우프로그래밍',25,'2015-01-02','2015-05-31',800,100);
INSERT INTO LECTURES(TITLE,CAPA,ST_DATE,ED_DATE,HOURS,DAYS)
VALUES('[윈도우51]윈도우프로그래밍',25,'2015-02-01','2015-06-30',800,100);

/* 강의실 및 사진 데이터 */
INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('강남','301');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('k301.gif',1);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('강남','303');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('k303.gif',2);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('강남','401');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('k401.gif',3);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('강남','402');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('k402.gif',4);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('강남','403');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('k403.gif',5);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('강남','404');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('k404.gif',6);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('강남','501');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('k501.gif',7);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('강남','502');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('k502.gif',8);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('강남','503');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('k503.gif',9);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('강남','504');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('k504.gif',10);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('종로','1호');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('j001.gif',11);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('종로','2호');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('j002.gif',12);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('종로','3호');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('j003.gif',13);

INSERT INTO CLASSROOMS(LOC,ROOM) VALUES('종로','4호');
INSERT INTO CR_PHOTO(PHOTO,CNO) VALUES('j004.gif',14);

/* 강의에 강의실 배정 */
/* [자바70]강의 : 강남 301 */
UPDATE LECTURES SET CNO=1 WHERE LNO=1;

/* [자바71]강의 : 강남 403 */
UPDATE LECTURES SET CNO=5 WHERE LNO=2;

/* [윈도우50]강의 : 종로 2호 */
UPDATE LECTURES SET CNO=12 WHERE LNO=4;





