/* 과목 데이터 */
INSERT INTO SUBJECTS(TITLE) VALUES('자바');
INSERT INTO SUBJECTS(TITLE) VALUES('C');
INSERT INTO SUBJECTS(TITLE) VALUES('C++');
INSERT INTO SUBJECTS(TITLE) VALUES('C#');
INSERT INTO SUBJECTS(TITLE) VALUES('안드로이드');
INSERT INTO SUBJECTS(TITLE) VALUES('HTML5');
INSERT INTO SUBJECTS(TITLE) VALUES('아두이노');
INSERT INTO SUBJECTS(TITLE) VALUES('서블릿/JSP');
INSERT INTO SUBJECTS(TITLE) VALUES('스프링 프레임워크');

/* 강사 데이터 */
INSERT INTO TRAINERS(NAME,PHOTO,TEL,EMAIL,PWD)
VALUES('홍길동','hong.gif','111-1111','hong@test.com','1111');
INSERT INTO TRAINERS(NAME,PHOTO,TEL,EMAIL,PWD)
VALUES('임꺽정','leem.gif','111-2222','leem@test.com','1111');
INSERT INTO TRAINERS(NAME,PHOTO,TEL,EMAIL,PWD)
VALUES('유관순','yoo.gif','111-3333','yoo@test.com','1111');
INSERT INTO TRAINERS(NAME,PHOTO,TEL,EMAIL,PWD)
VALUES('안중근','ahn.gif','111-4444','ahn@test.com','1111');
INSERT INTO TRAINERS(NAME,PHOTO,TEL,EMAIL,PWD)
VALUES('윤봉길','yoon.gif','111-5555','yoon@test.com','1111');

/* 강사가 강의할 수 있는 과목 데이터 */
/*홍길동 : 자바, C, C++*/
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(1,1);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(1,2);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(1,3);

/*임꺽정 : 안드로이디, 아두이노*/
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(2,5);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(2,7);

/*유관순 : 자바, HTML5*/
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(3,1);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(3,6);

/*안중근 : 자바, C, C++, 안드로이드, 아두이노*/
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(4,1);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(4,2);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(4,3);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(4,5);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(4,7);

/*윤봉길 : 자바, 서블릿JSP, 스프링 프레임워크 */
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(5,1);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(5,8);
INSERT INTO SUB_TRAI(TNO,SNO) VALUES(5,9);











